// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserMsg.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_UserMsg_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_UserMsg_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_UserMsg_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_UserMsg_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[6]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_UserMsg_2eproto;
namespace UserMsgProto {
class QueryUserMsgRequest;
class QueryUserMsgRequestDefaultTypeInternal;
extern QueryUserMsgRequestDefaultTypeInternal _QueryUserMsgRequest_default_instance_;
class QueryUserMsgResponse;
class QueryUserMsgResponseDefaultTypeInternal;
extern QueryUserMsgResponseDefaultTypeInternal _QueryUserMsgResponse_default_instance_;
class ResultCode;
class ResultCodeDefaultTypeInternal;
extern ResultCodeDefaultTypeInternal _ResultCode_default_instance_;
class UpdateUserMsgRequest;
class UpdateUserMsgRequestDefaultTypeInternal;
extern UpdateUserMsgRequestDefaultTypeInternal _UpdateUserMsgRequest_default_instance_;
class UpdateUserMsgResponse;
class UpdateUserMsgResponseDefaultTypeInternal;
extern UpdateUserMsgResponseDefaultTypeInternal _UpdateUserMsgResponse_default_instance_;
class UserInfo;
class UserInfoDefaultTypeInternal;
extern UserInfoDefaultTypeInternal _UserInfo_default_instance_;
}  // namespace UserMsgProto
PROTOBUF_NAMESPACE_OPEN
template<> ::UserMsgProto::QueryUserMsgRequest* Arena::CreateMaybeMessage<::UserMsgProto::QueryUserMsgRequest>(Arena*);
template<> ::UserMsgProto::QueryUserMsgResponse* Arena::CreateMaybeMessage<::UserMsgProto::QueryUserMsgResponse>(Arena*);
template<> ::UserMsgProto::ResultCode* Arena::CreateMaybeMessage<::UserMsgProto::ResultCode>(Arena*);
template<> ::UserMsgProto::UpdateUserMsgRequest* Arena::CreateMaybeMessage<::UserMsgProto::UpdateUserMsgRequest>(Arena*);
template<> ::UserMsgProto::UpdateUserMsgResponse* Arena::CreateMaybeMessage<::UserMsgProto::UpdateUserMsgResponse>(Arena*);
template<> ::UserMsgProto::UserInfo* Arena::CreateMaybeMessage<::UserMsgProto::UserInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace UserMsgProto {

// ===================================================================

class UserInfo :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:UserMsgProto.UserInfo) */ {
 public:
  UserInfo();
  virtual ~UserInfo();

  UserInfo(const UserInfo& from);
  UserInfo(UserInfo&& from) noexcept
    : UserInfo() {
    *this = ::std::move(from);
  }

  inline UserInfo& operator=(const UserInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline UserInfo& operator=(UserInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const UserInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UserInfo* internal_default_instance() {
    return reinterpret_cast<const UserInfo*>(
               &_UserInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(UserInfo& a, UserInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(UserInfo* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline UserInfo* New() const final {
    return CreateMaybeMessage<UserInfo>(nullptr);
  }

  UserInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<UserInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const UserInfo& from);
  void MergeFrom(const UserInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UserInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "UserMsgProto.UserInfo";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_UserMsg_2eproto);
    return ::descriptor_table_UserMsg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 2,
    kPwdFieldNumber = 3,
    kEmailFieldNumber = 4,
    kPhoneFieldNumber = 5,
    kDescFieldNumber = 6,
    kDepartNameFieldNumber = 7,
    kIdFieldNumber = 1,
  };
  // bytes name = 2;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const void* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // bytes pwd = 3;
  void clear_pwd();
  const std::string& pwd() const;
  void set_pwd(const std::string& value);
  void set_pwd(std::string&& value);
  void set_pwd(const char* value);
  void set_pwd(const void* value, size_t size);
  std::string* mutable_pwd();
  std::string* release_pwd();
  void set_allocated_pwd(std::string* pwd);
  private:
  const std::string& _internal_pwd() const;
  void _internal_set_pwd(const std::string& value);
  std::string* _internal_mutable_pwd();
  public:

  // bytes email = 4;
  void clear_email();
  const std::string& email() const;
  void set_email(const std::string& value);
  void set_email(std::string&& value);
  void set_email(const char* value);
  void set_email(const void* value, size_t size);
  std::string* mutable_email();
  std::string* release_email();
  void set_allocated_email(std::string* email);
  private:
  const std::string& _internal_email() const;
  void _internal_set_email(const std::string& value);
  std::string* _internal_mutable_email();
  public:

  // bytes phone = 5;
  void clear_phone();
  const std::string& phone() const;
  void set_phone(const std::string& value);
  void set_phone(std::string&& value);
  void set_phone(const char* value);
  void set_phone(const void* value, size_t size);
  std::string* mutable_phone();
  std::string* release_phone();
  void set_allocated_phone(std::string* phone);
  private:
  const std::string& _internal_phone() const;
  void _internal_set_phone(const std::string& value);
  std::string* _internal_mutable_phone();
  public:

  // bytes desc = 6;
  void clear_desc();
  const std::string& desc() const;
  void set_desc(const std::string& value);
  void set_desc(std::string&& value);
  void set_desc(const char* value);
  void set_desc(const void* value, size_t size);
  std::string* mutable_desc();
  std::string* release_desc();
  void set_allocated_desc(std::string* desc);
  private:
  const std::string& _internal_desc() const;
  void _internal_set_desc(const std::string& value);
  std::string* _internal_mutable_desc();
  public:

  // bytes departName = 7;
  void clear_departname();
  const std::string& departname() const;
  void set_departname(const std::string& value);
  void set_departname(std::string&& value);
  void set_departname(const char* value);
  void set_departname(const void* value, size_t size);
  std::string* mutable_departname();
  std::string* release_departname();
  void set_allocated_departname(std::string* departname);
  private:
  const std::string& _internal_departname() const;
  void _internal_set_departname(const std::string& value);
  std::string* _internal_mutable_departname();
  public:

  // int32 id = 1;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::int32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:UserMsgProto.UserInfo)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr pwd_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr email_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr phone_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr desc_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr departname_;
  ::PROTOBUF_NAMESPACE_ID::int32 id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_UserMsg_2eproto;
};
// -------------------------------------------------------------------

class ResultCode :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:UserMsgProto.ResultCode) */ {
 public:
  ResultCode();
  virtual ~ResultCode();

  ResultCode(const ResultCode& from);
  ResultCode(ResultCode&& from) noexcept
    : ResultCode() {
    *this = ::std::move(from);
  }

  inline ResultCode& operator=(const ResultCode& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResultCode& operator=(ResultCode&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ResultCode& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResultCode* internal_default_instance() {
    return reinterpret_cast<const ResultCode*>(
               &_ResultCode_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ResultCode& a, ResultCode& b) {
    a.Swap(&b);
  }
  inline void Swap(ResultCode* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ResultCode* New() const final {
    return CreateMaybeMessage<ResultCode>(nullptr);
  }

  ResultCode* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ResultCode>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ResultCode& from);
  void MergeFrom(const ResultCode& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResultCode* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "UserMsgProto.ResultCode";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_UserMsg_2eproto);
    return ::descriptor_table_UserMsg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrmsgFieldNumber = 2,
    kErrcodeFieldNumber = 1,
  };
  // bytes errmsg = 2;
  void clear_errmsg();
  const std::string& errmsg() const;
  void set_errmsg(const std::string& value);
  void set_errmsg(std::string&& value);
  void set_errmsg(const char* value);
  void set_errmsg(const void* value, size_t size);
  std::string* mutable_errmsg();
  std::string* release_errmsg();
  void set_allocated_errmsg(std::string* errmsg);
  private:
  const std::string& _internal_errmsg() const;
  void _internal_set_errmsg(const std::string& value);
  std::string* _internal_mutable_errmsg();
  public:

  // int32 errcode = 1;
  void clear_errcode();
  ::PROTOBUF_NAMESPACE_ID::int32 errcode() const;
  void set_errcode(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_errcode() const;
  void _internal_set_errcode(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:UserMsgProto.ResultCode)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr errmsg_;
  ::PROTOBUF_NAMESPACE_ID::int32 errcode_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_UserMsg_2eproto;
};
// -------------------------------------------------------------------

class QueryUserMsgRequest :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:UserMsgProto.QueryUserMsgRequest) */ {
 public:
  QueryUserMsgRequest();
  virtual ~QueryUserMsgRequest();

  QueryUserMsgRequest(const QueryUserMsgRequest& from);
  QueryUserMsgRequest(QueryUserMsgRequest&& from) noexcept
    : QueryUserMsgRequest() {
    *this = ::std::move(from);
  }

  inline QueryUserMsgRequest& operator=(const QueryUserMsgRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline QueryUserMsgRequest& operator=(QueryUserMsgRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const QueryUserMsgRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const QueryUserMsgRequest* internal_default_instance() {
    return reinterpret_cast<const QueryUserMsgRequest*>(
               &_QueryUserMsgRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(QueryUserMsgRequest& a, QueryUserMsgRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(QueryUserMsgRequest* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline QueryUserMsgRequest* New() const final {
    return CreateMaybeMessage<QueryUserMsgRequest>(nullptr);
  }

  QueryUserMsgRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<QueryUserMsgRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const QueryUserMsgRequest& from);
  void MergeFrom(const QueryUserMsgRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(QueryUserMsgRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "UserMsgProto.QueryUserMsgRequest";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_UserMsg_2eproto);
    return ::descriptor_table_UserMsg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
  };
  // bytes name = 1;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const void* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // @@protoc_insertion_point(class_scope:UserMsgProto.QueryUserMsgRequest)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_UserMsg_2eproto;
};
// -------------------------------------------------------------------

class QueryUserMsgResponse :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:UserMsgProto.QueryUserMsgResponse) */ {
 public:
  QueryUserMsgResponse();
  virtual ~QueryUserMsgResponse();

  QueryUserMsgResponse(const QueryUserMsgResponse& from);
  QueryUserMsgResponse(QueryUserMsgResponse&& from) noexcept
    : QueryUserMsgResponse() {
    *this = ::std::move(from);
  }

  inline QueryUserMsgResponse& operator=(const QueryUserMsgResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline QueryUserMsgResponse& operator=(QueryUserMsgResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const QueryUserMsgResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const QueryUserMsgResponse* internal_default_instance() {
    return reinterpret_cast<const QueryUserMsgResponse*>(
               &_QueryUserMsgResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(QueryUserMsgResponse& a, QueryUserMsgResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(QueryUserMsgResponse* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline QueryUserMsgResponse* New() const final {
    return CreateMaybeMessage<QueryUserMsgResponse>(nullptr);
  }

  QueryUserMsgResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<QueryUserMsgResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const QueryUserMsgResponse& from);
  void MergeFrom(const QueryUserMsgResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(QueryUserMsgResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "UserMsgProto.QueryUserMsgResponse";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_UserMsg_2eproto);
    return ::descriptor_table_UserMsg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResultFieldNumber = 1,
    kUserMsgFieldNumber = 2,
  };
  // .UserMsgProto.ResultCode result = 1;
  bool has_result() const;
  private:
  bool _internal_has_result() const;
  public:
  void clear_result();
  const ::UserMsgProto::ResultCode& result() const;
  ::UserMsgProto::ResultCode* release_result();
  ::UserMsgProto::ResultCode* mutable_result();
  void set_allocated_result(::UserMsgProto::ResultCode* result);
  private:
  const ::UserMsgProto::ResultCode& _internal_result() const;
  ::UserMsgProto::ResultCode* _internal_mutable_result();
  public:

  // .UserMsgProto.UserInfo userMsg = 2;
  bool has_usermsg() const;
  private:
  bool _internal_has_usermsg() const;
  public:
  void clear_usermsg();
  const ::UserMsgProto::UserInfo& usermsg() const;
  ::UserMsgProto::UserInfo* release_usermsg();
  ::UserMsgProto::UserInfo* mutable_usermsg();
  void set_allocated_usermsg(::UserMsgProto::UserInfo* usermsg);
  private:
  const ::UserMsgProto::UserInfo& _internal_usermsg() const;
  ::UserMsgProto::UserInfo* _internal_mutable_usermsg();
  public:

  // @@protoc_insertion_point(class_scope:UserMsgProto.QueryUserMsgResponse)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::UserMsgProto::ResultCode* result_;
  ::UserMsgProto::UserInfo* usermsg_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_UserMsg_2eproto;
};
// -------------------------------------------------------------------

class UpdateUserMsgRequest :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:UserMsgProto.UpdateUserMsgRequest) */ {
 public:
  UpdateUserMsgRequest();
  virtual ~UpdateUserMsgRequest();

  UpdateUserMsgRequest(const UpdateUserMsgRequest& from);
  UpdateUserMsgRequest(UpdateUserMsgRequest&& from) noexcept
    : UpdateUserMsgRequest() {
    *this = ::std::move(from);
  }

  inline UpdateUserMsgRequest& operator=(const UpdateUserMsgRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline UpdateUserMsgRequest& operator=(UpdateUserMsgRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const UpdateUserMsgRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UpdateUserMsgRequest* internal_default_instance() {
    return reinterpret_cast<const UpdateUserMsgRequest*>(
               &_UpdateUserMsgRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(UpdateUserMsgRequest& a, UpdateUserMsgRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(UpdateUserMsgRequest* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline UpdateUserMsgRequest* New() const final {
    return CreateMaybeMessage<UpdateUserMsgRequest>(nullptr);
  }

  UpdateUserMsgRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<UpdateUserMsgRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const UpdateUserMsgRequest& from);
  void MergeFrom(const UpdateUserMsgRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UpdateUserMsgRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "UserMsgProto.UpdateUserMsgRequest";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_UserMsg_2eproto);
    return ::descriptor_table_UserMsg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserMsgFieldNumber = 1,
  };
  // .UserMsgProto.UserInfo userMsg = 1;
  bool has_usermsg() const;
  private:
  bool _internal_has_usermsg() const;
  public:
  void clear_usermsg();
  const ::UserMsgProto::UserInfo& usermsg() const;
  ::UserMsgProto::UserInfo* release_usermsg();
  ::UserMsgProto::UserInfo* mutable_usermsg();
  void set_allocated_usermsg(::UserMsgProto::UserInfo* usermsg);
  private:
  const ::UserMsgProto::UserInfo& _internal_usermsg() const;
  ::UserMsgProto::UserInfo* _internal_mutable_usermsg();
  public:

  // @@protoc_insertion_point(class_scope:UserMsgProto.UpdateUserMsgRequest)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::UserMsgProto::UserInfo* usermsg_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_UserMsg_2eproto;
};
// -------------------------------------------------------------------

class UpdateUserMsgResponse :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:UserMsgProto.UpdateUserMsgResponse) */ {
 public:
  UpdateUserMsgResponse();
  virtual ~UpdateUserMsgResponse();

  UpdateUserMsgResponse(const UpdateUserMsgResponse& from);
  UpdateUserMsgResponse(UpdateUserMsgResponse&& from) noexcept
    : UpdateUserMsgResponse() {
    *this = ::std::move(from);
  }

  inline UpdateUserMsgResponse& operator=(const UpdateUserMsgResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline UpdateUserMsgResponse& operator=(UpdateUserMsgResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const UpdateUserMsgResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UpdateUserMsgResponse* internal_default_instance() {
    return reinterpret_cast<const UpdateUserMsgResponse*>(
               &_UpdateUserMsgResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(UpdateUserMsgResponse& a, UpdateUserMsgResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(UpdateUserMsgResponse* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline UpdateUserMsgResponse* New() const final {
    return CreateMaybeMessage<UpdateUserMsgResponse>(nullptr);
  }

  UpdateUserMsgResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<UpdateUserMsgResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const UpdateUserMsgResponse& from);
  void MergeFrom(const UpdateUserMsgResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UpdateUserMsgResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "UserMsgProto.UpdateUserMsgResponse";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_UserMsg_2eproto);
    return ::descriptor_table_UserMsg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResultFieldNumber = 1,
  };
  // .UserMsgProto.ResultCode result = 1;
  bool has_result() const;
  private:
  bool _internal_has_result() const;
  public:
  void clear_result();
  const ::UserMsgProto::ResultCode& result() const;
  ::UserMsgProto::ResultCode* release_result();
  ::UserMsgProto::ResultCode* mutable_result();
  void set_allocated_result(::UserMsgProto::ResultCode* result);
  private:
  const ::UserMsgProto::ResultCode& _internal_result() const;
  ::UserMsgProto::ResultCode* _internal_mutable_result();
  public:

  // @@protoc_insertion_point(class_scope:UserMsgProto.UpdateUserMsgResponse)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::UserMsgProto::ResultCode* result_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_UserMsg_2eproto;
};
// ===================================================================

class UserMsgServiceRpc_Stub;

class UserMsgServiceRpc : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline UserMsgServiceRpc() {};
 public:
  virtual ~UserMsgServiceRpc();

  typedef UserMsgServiceRpc_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void QueryUserMsg(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::UserMsgProto::QueryUserMsgRequest* request,
                       ::UserMsgProto::QueryUserMsgResponse* response,
                       ::google::protobuf::Closure* done);
  virtual void UpdateUserMsg(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::UserMsgProto::UpdateUserMsgRequest* request,
                       ::UserMsgProto::UpdateUserMsgResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(UserMsgServiceRpc);
};

class UserMsgServiceRpc_Stub : public UserMsgServiceRpc {
 public:
  UserMsgServiceRpc_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  UserMsgServiceRpc_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~UserMsgServiceRpc_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements UserMsgServiceRpc ------------------------------------------

  void QueryUserMsg(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::UserMsgProto::QueryUserMsgRequest* request,
                       ::UserMsgProto::QueryUserMsgResponse* response,
                       ::google::protobuf::Closure* done);
  void UpdateUserMsg(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::UserMsgProto::UpdateUserMsgRequest* request,
                       ::UserMsgProto::UpdateUserMsgResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(UserMsgServiceRpc_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// UserInfo

// int32 id = 1;
inline void UserInfo::clear_id() {
  id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 UserInfo::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 UserInfo::id() const {
  // @@protoc_insertion_point(field_get:UserMsgProto.UserInfo.id)
  return _internal_id();
}
inline void UserInfo::_internal_set_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  id_ = value;
}
inline void UserInfo::set_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:UserMsgProto.UserInfo.id)
}

// bytes name = 2;
inline void UserInfo::clear_name() {
  name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& UserInfo::name() const {
  // @@protoc_insertion_point(field_get:UserMsgProto.UserInfo.name)
  return _internal_name();
}
inline void UserInfo::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:UserMsgProto.UserInfo.name)
}
inline std::string* UserInfo::mutable_name() {
  // @@protoc_insertion_point(field_mutable:UserMsgProto.UserInfo.name)
  return _internal_mutable_name();
}
inline const std::string& UserInfo::_internal_name() const {
  return name_.GetNoArena();
}
inline void UserInfo::_internal_set_name(const std::string& value) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void UserInfo::set_name(std::string&& value) {
  
  name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:UserMsgProto.UserInfo.name)
}
inline void UserInfo::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:UserMsgProto.UserInfo.name)
}
inline void UserInfo::set_name(const void* value, size_t size) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:UserMsgProto.UserInfo.name)
}
inline std::string* UserInfo::_internal_mutable_name() {
  
  return name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* UserInfo::release_name() {
  // @@protoc_insertion_point(field_release:UserMsgProto.UserInfo.name)
  
  return name_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void UserInfo::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:UserMsgProto.UserInfo.name)
}

// bytes pwd = 3;
inline void UserInfo::clear_pwd() {
  pwd_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& UserInfo::pwd() const {
  // @@protoc_insertion_point(field_get:UserMsgProto.UserInfo.pwd)
  return _internal_pwd();
}
inline void UserInfo::set_pwd(const std::string& value) {
  _internal_set_pwd(value);
  // @@protoc_insertion_point(field_set:UserMsgProto.UserInfo.pwd)
}
inline std::string* UserInfo::mutable_pwd() {
  // @@protoc_insertion_point(field_mutable:UserMsgProto.UserInfo.pwd)
  return _internal_mutable_pwd();
}
inline const std::string& UserInfo::_internal_pwd() const {
  return pwd_.GetNoArena();
}
inline void UserInfo::_internal_set_pwd(const std::string& value) {
  
  pwd_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void UserInfo::set_pwd(std::string&& value) {
  
  pwd_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:UserMsgProto.UserInfo.pwd)
}
inline void UserInfo::set_pwd(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  pwd_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:UserMsgProto.UserInfo.pwd)
}
inline void UserInfo::set_pwd(const void* value, size_t size) {
  
  pwd_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:UserMsgProto.UserInfo.pwd)
}
inline std::string* UserInfo::_internal_mutable_pwd() {
  
  return pwd_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* UserInfo::release_pwd() {
  // @@protoc_insertion_point(field_release:UserMsgProto.UserInfo.pwd)
  
  return pwd_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void UserInfo::set_allocated_pwd(std::string* pwd) {
  if (pwd != nullptr) {
    
  } else {
    
  }
  pwd_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), pwd);
  // @@protoc_insertion_point(field_set_allocated:UserMsgProto.UserInfo.pwd)
}

// bytes email = 4;
inline void UserInfo::clear_email() {
  email_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& UserInfo::email() const {
  // @@protoc_insertion_point(field_get:UserMsgProto.UserInfo.email)
  return _internal_email();
}
inline void UserInfo::set_email(const std::string& value) {
  _internal_set_email(value);
  // @@protoc_insertion_point(field_set:UserMsgProto.UserInfo.email)
}
inline std::string* UserInfo::mutable_email() {
  // @@protoc_insertion_point(field_mutable:UserMsgProto.UserInfo.email)
  return _internal_mutable_email();
}
inline const std::string& UserInfo::_internal_email() const {
  return email_.GetNoArena();
}
inline void UserInfo::_internal_set_email(const std::string& value) {
  
  email_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void UserInfo::set_email(std::string&& value) {
  
  email_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:UserMsgProto.UserInfo.email)
}
inline void UserInfo::set_email(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  email_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:UserMsgProto.UserInfo.email)
}
inline void UserInfo::set_email(const void* value, size_t size) {
  
  email_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:UserMsgProto.UserInfo.email)
}
inline std::string* UserInfo::_internal_mutable_email() {
  
  return email_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* UserInfo::release_email() {
  // @@protoc_insertion_point(field_release:UserMsgProto.UserInfo.email)
  
  return email_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void UserInfo::set_allocated_email(std::string* email) {
  if (email != nullptr) {
    
  } else {
    
  }
  email_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), email);
  // @@protoc_insertion_point(field_set_allocated:UserMsgProto.UserInfo.email)
}

// bytes phone = 5;
inline void UserInfo::clear_phone() {
  phone_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& UserInfo::phone() const {
  // @@protoc_insertion_point(field_get:UserMsgProto.UserInfo.phone)
  return _internal_phone();
}
inline void UserInfo::set_phone(const std::string& value) {
  _internal_set_phone(value);
  // @@protoc_insertion_point(field_set:UserMsgProto.UserInfo.phone)
}
inline std::string* UserInfo::mutable_phone() {
  // @@protoc_insertion_point(field_mutable:UserMsgProto.UserInfo.phone)
  return _internal_mutable_phone();
}
inline const std::string& UserInfo::_internal_phone() const {
  return phone_.GetNoArena();
}
inline void UserInfo::_internal_set_phone(const std::string& value) {
  
  phone_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void UserInfo::set_phone(std::string&& value) {
  
  phone_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:UserMsgProto.UserInfo.phone)
}
inline void UserInfo::set_phone(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  phone_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:UserMsgProto.UserInfo.phone)
}
inline void UserInfo::set_phone(const void* value, size_t size) {
  
  phone_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:UserMsgProto.UserInfo.phone)
}
inline std::string* UserInfo::_internal_mutable_phone() {
  
  return phone_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* UserInfo::release_phone() {
  // @@protoc_insertion_point(field_release:UserMsgProto.UserInfo.phone)
  
  return phone_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void UserInfo::set_allocated_phone(std::string* phone) {
  if (phone != nullptr) {
    
  } else {
    
  }
  phone_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), phone);
  // @@protoc_insertion_point(field_set_allocated:UserMsgProto.UserInfo.phone)
}

// bytes desc = 6;
inline void UserInfo::clear_desc() {
  desc_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& UserInfo::desc() const {
  // @@protoc_insertion_point(field_get:UserMsgProto.UserInfo.desc)
  return _internal_desc();
}
inline void UserInfo::set_desc(const std::string& value) {
  _internal_set_desc(value);
  // @@protoc_insertion_point(field_set:UserMsgProto.UserInfo.desc)
}
inline std::string* UserInfo::mutable_desc() {
  // @@protoc_insertion_point(field_mutable:UserMsgProto.UserInfo.desc)
  return _internal_mutable_desc();
}
inline const std::string& UserInfo::_internal_desc() const {
  return desc_.GetNoArena();
}
inline void UserInfo::_internal_set_desc(const std::string& value) {
  
  desc_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void UserInfo::set_desc(std::string&& value) {
  
  desc_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:UserMsgProto.UserInfo.desc)
}
inline void UserInfo::set_desc(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  desc_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:UserMsgProto.UserInfo.desc)
}
inline void UserInfo::set_desc(const void* value, size_t size) {
  
  desc_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:UserMsgProto.UserInfo.desc)
}
inline std::string* UserInfo::_internal_mutable_desc() {
  
  return desc_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* UserInfo::release_desc() {
  // @@protoc_insertion_point(field_release:UserMsgProto.UserInfo.desc)
  
  return desc_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void UserInfo::set_allocated_desc(std::string* desc) {
  if (desc != nullptr) {
    
  } else {
    
  }
  desc_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), desc);
  // @@protoc_insertion_point(field_set_allocated:UserMsgProto.UserInfo.desc)
}

// bytes departName = 7;
inline void UserInfo::clear_departname() {
  departname_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& UserInfo::departname() const {
  // @@protoc_insertion_point(field_get:UserMsgProto.UserInfo.departName)
  return _internal_departname();
}
inline void UserInfo::set_departname(const std::string& value) {
  _internal_set_departname(value);
  // @@protoc_insertion_point(field_set:UserMsgProto.UserInfo.departName)
}
inline std::string* UserInfo::mutable_departname() {
  // @@protoc_insertion_point(field_mutable:UserMsgProto.UserInfo.departName)
  return _internal_mutable_departname();
}
inline const std::string& UserInfo::_internal_departname() const {
  return departname_.GetNoArena();
}
inline void UserInfo::_internal_set_departname(const std::string& value) {
  
  departname_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void UserInfo::set_departname(std::string&& value) {
  
  departname_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:UserMsgProto.UserInfo.departName)
}
inline void UserInfo::set_departname(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  departname_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:UserMsgProto.UserInfo.departName)
}
inline void UserInfo::set_departname(const void* value, size_t size) {
  
  departname_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:UserMsgProto.UserInfo.departName)
}
inline std::string* UserInfo::_internal_mutable_departname() {
  
  return departname_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* UserInfo::release_departname() {
  // @@protoc_insertion_point(field_release:UserMsgProto.UserInfo.departName)
  
  return departname_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void UserInfo::set_allocated_departname(std::string* departname) {
  if (departname != nullptr) {
    
  } else {
    
  }
  departname_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), departname);
  // @@protoc_insertion_point(field_set_allocated:UserMsgProto.UserInfo.departName)
}

// -------------------------------------------------------------------

// ResultCode

// int32 errcode = 1;
inline void ResultCode::clear_errcode() {
  errcode_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ResultCode::_internal_errcode() const {
  return errcode_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ResultCode::errcode() const {
  // @@protoc_insertion_point(field_get:UserMsgProto.ResultCode.errcode)
  return _internal_errcode();
}
inline void ResultCode::_internal_set_errcode(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  errcode_ = value;
}
inline void ResultCode::set_errcode(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_errcode(value);
  // @@protoc_insertion_point(field_set:UserMsgProto.ResultCode.errcode)
}

// bytes errmsg = 2;
inline void ResultCode::clear_errmsg() {
  errmsg_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& ResultCode::errmsg() const {
  // @@protoc_insertion_point(field_get:UserMsgProto.ResultCode.errmsg)
  return _internal_errmsg();
}
inline void ResultCode::set_errmsg(const std::string& value) {
  _internal_set_errmsg(value);
  // @@protoc_insertion_point(field_set:UserMsgProto.ResultCode.errmsg)
}
inline std::string* ResultCode::mutable_errmsg() {
  // @@protoc_insertion_point(field_mutable:UserMsgProto.ResultCode.errmsg)
  return _internal_mutable_errmsg();
}
inline const std::string& ResultCode::_internal_errmsg() const {
  return errmsg_.GetNoArena();
}
inline void ResultCode::_internal_set_errmsg(const std::string& value) {
  
  errmsg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void ResultCode::set_errmsg(std::string&& value) {
  
  errmsg_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:UserMsgProto.ResultCode.errmsg)
}
inline void ResultCode::set_errmsg(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  errmsg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:UserMsgProto.ResultCode.errmsg)
}
inline void ResultCode::set_errmsg(const void* value, size_t size) {
  
  errmsg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:UserMsgProto.ResultCode.errmsg)
}
inline std::string* ResultCode::_internal_mutable_errmsg() {
  
  return errmsg_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ResultCode::release_errmsg() {
  // @@protoc_insertion_point(field_release:UserMsgProto.ResultCode.errmsg)
  
  return errmsg_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ResultCode::set_allocated_errmsg(std::string* errmsg) {
  if (errmsg != nullptr) {
    
  } else {
    
  }
  errmsg_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), errmsg);
  // @@protoc_insertion_point(field_set_allocated:UserMsgProto.ResultCode.errmsg)
}

// -------------------------------------------------------------------

// QueryUserMsgRequest

// bytes name = 1;
inline void QueryUserMsgRequest::clear_name() {
  name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& QueryUserMsgRequest::name() const {
  // @@protoc_insertion_point(field_get:UserMsgProto.QueryUserMsgRequest.name)
  return _internal_name();
}
inline void QueryUserMsgRequest::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:UserMsgProto.QueryUserMsgRequest.name)
}
inline std::string* QueryUserMsgRequest::mutable_name() {
  // @@protoc_insertion_point(field_mutable:UserMsgProto.QueryUserMsgRequest.name)
  return _internal_mutable_name();
}
inline const std::string& QueryUserMsgRequest::_internal_name() const {
  return name_.GetNoArena();
}
inline void QueryUserMsgRequest::_internal_set_name(const std::string& value) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void QueryUserMsgRequest::set_name(std::string&& value) {
  
  name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:UserMsgProto.QueryUserMsgRequest.name)
}
inline void QueryUserMsgRequest::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:UserMsgProto.QueryUserMsgRequest.name)
}
inline void QueryUserMsgRequest::set_name(const void* value, size_t size) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:UserMsgProto.QueryUserMsgRequest.name)
}
inline std::string* QueryUserMsgRequest::_internal_mutable_name() {
  
  return name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* QueryUserMsgRequest::release_name() {
  // @@protoc_insertion_point(field_release:UserMsgProto.QueryUserMsgRequest.name)
  
  return name_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void QueryUserMsgRequest::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:UserMsgProto.QueryUserMsgRequest.name)
}

// -------------------------------------------------------------------

// QueryUserMsgResponse

// .UserMsgProto.ResultCode result = 1;
inline bool QueryUserMsgResponse::_internal_has_result() const {
  return this != internal_default_instance() && result_ != nullptr;
}
inline bool QueryUserMsgResponse::has_result() const {
  return _internal_has_result();
}
inline void QueryUserMsgResponse::clear_result() {
  if (GetArenaNoVirtual() == nullptr && result_ != nullptr) {
    delete result_;
  }
  result_ = nullptr;
}
inline const ::UserMsgProto::ResultCode& QueryUserMsgResponse::_internal_result() const {
  const ::UserMsgProto::ResultCode* p = result_;
  return p != nullptr ? *p : *reinterpret_cast<const ::UserMsgProto::ResultCode*>(
      &::UserMsgProto::_ResultCode_default_instance_);
}
inline const ::UserMsgProto::ResultCode& QueryUserMsgResponse::result() const {
  // @@protoc_insertion_point(field_get:UserMsgProto.QueryUserMsgResponse.result)
  return _internal_result();
}
inline ::UserMsgProto::ResultCode* QueryUserMsgResponse::release_result() {
  // @@protoc_insertion_point(field_release:UserMsgProto.QueryUserMsgResponse.result)
  
  ::UserMsgProto::ResultCode* temp = result_;
  result_ = nullptr;
  return temp;
}
inline ::UserMsgProto::ResultCode* QueryUserMsgResponse::_internal_mutable_result() {
  
  if (result_ == nullptr) {
    auto* p = CreateMaybeMessage<::UserMsgProto::ResultCode>(GetArenaNoVirtual());
    result_ = p;
  }
  return result_;
}
inline ::UserMsgProto::ResultCode* QueryUserMsgResponse::mutable_result() {
  // @@protoc_insertion_point(field_mutable:UserMsgProto.QueryUserMsgResponse.result)
  return _internal_mutable_result();
}
inline void QueryUserMsgResponse::set_allocated_result(::UserMsgProto::ResultCode* result) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete result_;
  }
  if (result) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      result = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, result, submessage_arena);
    }
    
  } else {
    
  }
  result_ = result;
  // @@protoc_insertion_point(field_set_allocated:UserMsgProto.QueryUserMsgResponse.result)
}

// .UserMsgProto.UserInfo userMsg = 2;
inline bool QueryUserMsgResponse::_internal_has_usermsg() const {
  return this != internal_default_instance() && usermsg_ != nullptr;
}
inline bool QueryUserMsgResponse::has_usermsg() const {
  return _internal_has_usermsg();
}
inline void QueryUserMsgResponse::clear_usermsg() {
  if (GetArenaNoVirtual() == nullptr && usermsg_ != nullptr) {
    delete usermsg_;
  }
  usermsg_ = nullptr;
}
inline const ::UserMsgProto::UserInfo& QueryUserMsgResponse::_internal_usermsg() const {
  const ::UserMsgProto::UserInfo* p = usermsg_;
  return p != nullptr ? *p : *reinterpret_cast<const ::UserMsgProto::UserInfo*>(
      &::UserMsgProto::_UserInfo_default_instance_);
}
inline const ::UserMsgProto::UserInfo& QueryUserMsgResponse::usermsg() const {
  // @@protoc_insertion_point(field_get:UserMsgProto.QueryUserMsgResponse.userMsg)
  return _internal_usermsg();
}
inline ::UserMsgProto::UserInfo* QueryUserMsgResponse::release_usermsg() {
  // @@protoc_insertion_point(field_release:UserMsgProto.QueryUserMsgResponse.userMsg)
  
  ::UserMsgProto::UserInfo* temp = usermsg_;
  usermsg_ = nullptr;
  return temp;
}
inline ::UserMsgProto::UserInfo* QueryUserMsgResponse::_internal_mutable_usermsg() {
  
  if (usermsg_ == nullptr) {
    auto* p = CreateMaybeMessage<::UserMsgProto::UserInfo>(GetArenaNoVirtual());
    usermsg_ = p;
  }
  return usermsg_;
}
inline ::UserMsgProto::UserInfo* QueryUserMsgResponse::mutable_usermsg() {
  // @@protoc_insertion_point(field_mutable:UserMsgProto.QueryUserMsgResponse.userMsg)
  return _internal_mutable_usermsg();
}
inline void QueryUserMsgResponse::set_allocated_usermsg(::UserMsgProto::UserInfo* usermsg) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete usermsg_;
  }
  if (usermsg) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      usermsg = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, usermsg, submessage_arena);
    }
    
  } else {
    
  }
  usermsg_ = usermsg;
  // @@protoc_insertion_point(field_set_allocated:UserMsgProto.QueryUserMsgResponse.userMsg)
}

// -------------------------------------------------------------------

// UpdateUserMsgRequest

// .UserMsgProto.UserInfo userMsg = 1;
inline bool UpdateUserMsgRequest::_internal_has_usermsg() const {
  return this != internal_default_instance() && usermsg_ != nullptr;
}
inline bool UpdateUserMsgRequest::has_usermsg() const {
  return _internal_has_usermsg();
}
inline void UpdateUserMsgRequest::clear_usermsg() {
  if (GetArenaNoVirtual() == nullptr && usermsg_ != nullptr) {
    delete usermsg_;
  }
  usermsg_ = nullptr;
}
inline const ::UserMsgProto::UserInfo& UpdateUserMsgRequest::_internal_usermsg() const {
  const ::UserMsgProto::UserInfo* p = usermsg_;
  return p != nullptr ? *p : *reinterpret_cast<const ::UserMsgProto::UserInfo*>(
      &::UserMsgProto::_UserInfo_default_instance_);
}
inline const ::UserMsgProto::UserInfo& UpdateUserMsgRequest::usermsg() const {
  // @@protoc_insertion_point(field_get:UserMsgProto.UpdateUserMsgRequest.userMsg)
  return _internal_usermsg();
}
inline ::UserMsgProto::UserInfo* UpdateUserMsgRequest::release_usermsg() {
  // @@protoc_insertion_point(field_release:UserMsgProto.UpdateUserMsgRequest.userMsg)
  
  ::UserMsgProto::UserInfo* temp = usermsg_;
  usermsg_ = nullptr;
  return temp;
}
inline ::UserMsgProto::UserInfo* UpdateUserMsgRequest::_internal_mutable_usermsg() {
  
  if (usermsg_ == nullptr) {
    auto* p = CreateMaybeMessage<::UserMsgProto::UserInfo>(GetArenaNoVirtual());
    usermsg_ = p;
  }
  return usermsg_;
}
inline ::UserMsgProto::UserInfo* UpdateUserMsgRequest::mutable_usermsg() {
  // @@protoc_insertion_point(field_mutable:UserMsgProto.UpdateUserMsgRequest.userMsg)
  return _internal_mutable_usermsg();
}
inline void UpdateUserMsgRequest::set_allocated_usermsg(::UserMsgProto::UserInfo* usermsg) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete usermsg_;
  }
  if (usermsg) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      usermsg = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, usermsg, submessage_arena);
    }
    
  } else {
    
  }
  usermsg_ = usermsg;
  // @@protoc_insertion_point(field_set_allocated:UserMsgProto.UpdateUserMsgRequest.userMsg)
}

// -------------------------------------------------------------------

// UpdateUserMsgResponse

// .UserMsgProto.ResultCode result = 1;
inline bool UpdateUserMsgResponse::_internal_has_result() const {
  return this != internal_default_instance() && result_ != nullptr;
}
inline bool UpdateUserMsgResponse::has_result() const {
  return _internal_has_result();
}
inline void UpdateUserMsgResponse::clear_result() {
  if (GetArenaNoVirtual() == nullptr && result_ != nullptr) {
    delete result_;
  }
  result_ = nullptr;
}
inline const ::UserMsgProto::ResultCode& UpdateUserMsgResponse::_internal_result() const {
  const ::UserMsgProto::ResultCode* p = result_;
  return p != nullptr ? *p : *reinterpret_cast<const ::UserMsgProto::ResultCode*>(
      &::UserMsgProto::_ResultCode_default_instance_);
}
inline const ::UserMsgProto::ResultCode& UpdateUserMsgResponse::result() const {
  // @@protoc_insertion_point(field_get:UserMsgProto.UpdateUserMsgResponse.result)
  return _internal_result();
}
inline ::UserMsgProto::ResultCode* UpdateUserMsgResponse::release_result() {
  // @@protoc_insertion_point(field_release:UserMsgProto.UpdateUserMsgResponse.result)
  
  ::UserMsgProto::ResultCode* temp = result_;
  result_ = nullptr;
  return temp;
}
inline ::UserMsgProto::ResultCode* UpdateUserMsgResponse::_internal_mutable_result() {
  
  if (result_ == nullptr) {
    auto* p = CreateMaybeMessage<::UserMsgProto::ResultCode>(GetArenaNoVirtual());
    result_ = p;
  }
  return result_;
}
inline ::UserMsgProto::ResultCode* UpdateUserMsgResponse::mutable_result() {
  // @@protoc_insertion_point(field_mutable:UserMsgProto.UpdateUserMsgResponse.result)
  return _internal_mutable_result();
}
inline void UpdateUserMsgResponse::set_allocated_result(::UserMsgProto::ResultCode* result) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete result_;
  }
  if (result) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      result = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, result, submessage_arena);
    }
    
  } else {
    
  }
  result_ = result;
  // @@protoc_insertion_point(field_set_allocated:UserMsgProto.UpdateUserMsgResponse.result)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace UserMsgProto

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_UserMsg_2eproto
